### ISSUE TITLE
AOE crash zone in server, cannot connect without a crash

### ISSUE THREAD

**Issue by samsaq** [wormzjl/Project-PFAA#10]
AOE crash zone in server from the dropping of a rockMMR (chiseled cobble) block, which seems to have corrupted my inventory (crafted it with chisel, insta crash unless block in invetory, also)
crashlog link here : https://gist.github.com/anonymous/d869d9097e63325d020411955a00924d

**Comment by samsaq** [comment]
also, version number is the most current one (the one the server uses)

**Comment by wormzjl** [comment]
did you craft it in creative mode

**Comment by samsaq** [comment]
no, crafted it in the server itself, using a chisel

**Comment by samsaq** [comment]
also, if it helps, the original block was made from gabrro cobble, though I don't think it changes what it can be chiseled into vs the other cobbles.

**Comment by wormzjl** [comment]
can your try to clean the dropped item with some sort of admin commands or using mcedit?

**Comment by samsaq** [comment]
don't have admin or anything, sorry, to clarify, i'm in the rising kingdom server for the modpack, which I don't run, I just play there

**Comment by ghost** [comment]
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Chisel_2_Support
This may fix the issue in chisel if you remove the generic rock types from being obtainable
Specifically (adapt as necessary):  
`mods.chisel.Groups.removeVariation(<chisel:hexPlating>);`

**Comment by wormzjl** [comment]
not really familiar with this, gonna test tomorrow

**Comment by samsaq** [comment]
here's a link from baga for the exact name of the block, and the chisel block, etc it was from : https://media.discordapp.net/attachments/373983954103042048/396105473473904651/2017-12-28_19.59.30.png?width=884&height=469

**Comment by samsaq** [comment]
also, the block itself wasn't the issue, the rock that it dropped caused the crash itself, at least thats when I crashed

**Comment by wormzjl** [comment]
Not really able to fix this, but I have 2 workarounds:
1. remove cobbleStone variations from chisel
2. remove tfc cobbleStone oredict tags

**Comment by wormzjl** [comment]
option 2 works
