### ISSUE TITLE
Chiseled form of Gabboro crashed game upon opening inv or having it on ground as item

### ISSUE THREAD

**Issue by saqib126** [wormzjl/Project-PFAA#11]
Both myself and samsaq were playing on the Rising Kingdom server when he decided to chisel some Gabboro Cobblstone into rock.mmr.[something goes here, he couldn't read in time] and upon open his inventory crashed the game. When i killed him(he rejoined but didn't open inv) and he tried to open his grave and salvage some of his inventory it spilled out onto the ground and crashed us both, and does so near instantly upon us joining the server again. If you could delete the item that causes this and stop anyone else from running into this problem, please do so.

Link to crash report: https://gist.github.com/anonymous/5fac95ceb46c9f4ab49bdc73a67451ae

**Comment by saqib126** [comment]
Version is 1.0.7

**Comment by wormzjl** [comment]
can't delete this thing, but I've prevented chiseling into this corrupted block in new version
