### ISSUE TITLE
Problem Coke oven brick

### ISSUE THREAD

**Issue by jcarrest** [wormzjl/Project-PFAA#17]
I have tried different types of sand with clay brick.
Do not believe it.
In the NEI it appears, but it does not indicate a recipe to do it.
The original recipe does not work. Sand (52)
Any idea what can happen?
thanks

**Comment by wormzjl** [comment]
tfc sand can be converted to vanilla sand in the crafting grid, use that one

**Comment by jcarrest** [comment]
Thank you
I have created sand vanilla but the coke oven recipe does not work ...

**Comment by wormzjl** [comment]
Give me some screenshots?

jcarrest <notifications@github.com> 于 2018年3月26日周一 18:32写道：

**Comment by jcarrest** [comment]
![1](https://user-images.githubusercontent.com/37738569/38239648-a152edac-372d-11e8-8572-d95898838312.jpg)
![2](https://user-images.githubusercontent.com/37738569/38239649-a175ff4a-372d-11e8-95bf-050bb9f0c7d5.jpg)

**Comment by spacewolfcub** [comment]
This is what my NEI shows, and it works:

![screenshot 2018-04-03 03 53 12](https://user-images.githubusercontent.com/11811417/38245526-3f0e664c-36f3-11e8-86ce-f27dc7f2ff85.png)
![screenshot 2018-04-03 03 53 18](https://user-images.githubusercontent.com/11811417/38245532-4228f400-36f3-11e8-88df-6f0cf4f8483f.png)
![screenshot 2018-04-03 03 53 36](https://user-images.githubusercontent.com/11811417/38245536-44a7b068-36f3-11e8-9fbf-a2296bbc78be.png)

**Comment by wormzjl** [comment]
well, always check nei for recipes :P

**Comment by jcarrest** [comment]
the nei does not say recipe. that's why I think it does not let me create.
:)

**Comment by jcarrest** [comment]
also with that brick I can not do coke oven

**Comment by wormzjl** [comment]
Try backup your world and do a fresh install of this pack



jcarrest <notifications@github.com> 于 2018年4月3日周二 16:10写道：
