### ISSUE TITLE
Advanced Plating can be returned as diamonds

### ISSUE THREAD

**Issue by nickseo7** [wormzjl/Project-PFAA#22]
![2018-07-28_22 45 30](https://user-images.githubusercontent.com/37957120/43357216-f7d10574-92b8-11e8-91e4-90e6b4a31a04.png)
As I was new to the pack, I've been looking around how recipes are changed. Then I found this problem even after I had done /mt reload.

And additionally, Malisis' Doors doesn't seem to support any of TFC plank/ingot at all. I wonder if it's intended or not.

(English is not my mother language, so apologize for a chance of miscommunication.)

**Comment by wormzjl** [comment]
fixed
