### ISSUE TITLE
Few Minor Bugs

### ISSUE THREAD

**Issue by nickseo7** [wormzjl/Project-PFAA#23]
The Precision Sawmill disassembles Bed to its vanilla crafting ingredients.
![2018-07-29_14 17 37](https://user-images.githubusercontent.com/37957120/43363931-f033be82-934a-11e8-852f-e8724da28d21.png)
![2018-07-29_14 17 33](https://user-images.githubusercontent.com/37957120/43363932-f1ab7f0c-934a-11e8-8e08-217459ac121c.png)

A recipe(seems like made for Buildcraft Quarry recipe) can make fire.
![2018-07-29_14 18 47](https://user-images.githubusercontent.com/37957120/43363933-f4c67bd8-934a-11e8-80e3-47214cf0b3e6.png)

Vanilla Clay and Quartz can't be converted to TFC ones, unlike Charcoal.

Vanilla Bone Meal can be crafted through various recipes, but it can make industrial hemp grow faster, so it would be nice to exchange those recipes(Crusher, Grindstone, etc...) to make TFC Bone Meal. If then, tweaks for firework recipes and two recipes below should be needed.
![2018-07-29_16 49 43](https://user-images.githubusercontent.com/37957120/43364203-e313b4b8-9350-11e8-89d9-81757f2280d2.png)
![2018-07-29_16 47 16](https://user-images.githubusercontent.com/37957120/43364219-13a8593a-9351-11e8-8047-750c3cec4c92.png)

Charged Quartz Fixture and Light Detecting Fixture is using only vanilla Iron Ingot.
![2018-07-29_16 36 39](https://user-images.githubusercontent.com/37957120/43364066-edac39e8-934d-11e8-962a-17b6dc1b527b.png)
![2018-07-29_16 36 45](https://user-images.githubusercontent.com/37957120/43364067-f06d9e38-934d-11e8-939a-b978396d243f.png)

**Comment by nickseo7** [comment]
![2018-07-29_17 19 31](https://user-images.githubusercontent.com/37957120/43364351-9462f1b4-9353-11e8-91c1-3aef87b97741.png)
Can this also be tweakable?(Factorization Recipe)

**Comment by wormzjl** [comment]
implemented
