### ISSUE TITLE
New Versions of TFC

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [wormzjl/Project-PFAA#24]
There is a new release of TFC with bugfixes and performance improvements:
https://minecraft.curseforge.com/projects/tfcraft/files/2627990
https://github.com/TerraFirmaCraft/TFC-1.7.10

There is also TFC+ which is adding new features:
https://minecraft.curseforge.com/projects/terrafirmacraftplus?gameCategorySlug=mc-mods&projectID=287053
https://www.reddit.com/r/tfcplus

**Comment by wormzjl** [comment]
implemented, please report if anything breaks
