### ISSUE TITLE
How to get paper?

### ISSUE THREAD

**Issue by RomkeVdMeulen** [wormzjl/Project-PFAA#36]
For the Induction Smelter I need a circuit board, which needs paper to build. But I can't find a recipe for paper I have access to right now - it all requires forestry or mekanism machines. Is there some hint I've missed about how to get paper?

**Comment by Sukasa** [comment]
You need to use paper presses, see https://terrafirmacraft.com/f/topic/9902-primitive-technology-tfc-add-on-mod/ .

As well, the GitHub issues are meant for bugs in the pack, not general help.  You'll have a much better time if you join the Discord server instead :)

**Comment by RomkeVdMeulen** [comment]
Ah, I see. Apologies!
