### ISSUE TITLE
Immersive Engeering charcoal not working as expected

### ISSUE THREAD

**Issue by Turmfalke2** [wormzjl/Project-PFAA#8]
hi,
The quest book tells me to make the immersive engineering coke oven for a better way of making charcoal, however the charcoal from the IE can't be used interchangeable with the TFC charcoal.

**Comment by wormzjl** [comment]
![image](https://user-images.githubusercontent.com/2989009/33573430-12754b66-d936-11e7-868a-b2b15b0915c1.png)
Use this recipe

**Comment by Turmfalke2** [comment]
Right.. ok.
